databases:
  - name: testtodo
    databaseName: testtodo_production
    user: testtodo_production_user
    region: singapore

services:
  - type: web
    name: testtodo
    env: ruby
    region: singapore
    plan: free
    # buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: testtodo_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false